plugins:
  - jekyll-archives
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-jupyter-notebook
  - jekyll-link-attributes
  - jekyll-paginate-v2
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-toc
  - jemoji

external_sources: []

exclude:
  - bin
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - docker-compose.yml
  - Dockerfile
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - INSTALL.md
  - LICENSE
  - package.json
  - package-lock.json
  - purgecss.config.js
  - README.md
  - vendor
  - _posts/2020-09-28-twitter.md
